runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /
  script: controllers.home.app

- url: /edit-profile
  script: request.account.app

- url: /profile
  script: request.profile.app

- url: /search_user
  script: request.search.app

- url: /search_tweet
  script: request.search.app

- url: /delete-tweet
  script: request.profile.app

- url: /edit-tweet
  script: request.profile.app


- url: /assets
  static_dir: assets
